###
POST http://localhost:5000/api/lessons/assign-lesson
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMzMwMDY1ZS1iODIzLTRjOTEtOTI4YS03ODAzMGFiYzhmOTAiLCJpYXQiOjE3NTI4NDY0MzMsImV4cCI6MTc1MjkzMjgzM30.0brNcNemGHJcUzvFTpX8Bh7teOr1-Qqm9OMaRH5rfYk
Content-Type: application/json

{
  "title": "Lesson 1",
  "description": "Lesson 1 description",
  "studentPhones": ["0933131464", "0933131465"]
}