###
GET http://localhost:5000/api/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNmY0MjQ2ZC04OWVkLTRjMTYtYmMyOS1iYWE1MTdmOGViNjYiLCJpYXQiOjE3NTI4NDI2NjksImV4cCI6MTc1MjkyOTA2OX0.I2BrGdy55VbJoIzT7Gqby4-N05TNCt-mgqsIYf30wlI


###
POST http://localhost:5000/api/auth/send-code
Content-Type: application/json

{
  "type": "phone",
  "identifier": "0933131464"
}

###
POST http://localhost:5000/api/auth/send-sms
Content-Type: application/json

{
  "type": "username",
  "identifier": "kingchen711"
}

###
POST http://localhost:5000/api/auth/validate-access-code
Content-Type: application/json

{
  "phoneNumber": "0123456789",
  "accessCode": "457904"
}

###
GET http://localhost:5000/api/auth/setup/verify/aa15b118ec81731a0d0fa9d03c57ef58bdd8540995248d62edea99ec03184532

###
POST http://localhost:5000/api/auth/setup/complete
Content-Type: application/json

{
  "token": "aa15b118ec81731a0d0fa9d03c57ef58bdd8540995248d62edea99ec03184532",
  "username": "kingchen711",
  "password": "123456"
}

###
POST http://localhost:5000/api/auth/check-exist-account
Content-Type: application/json

{
  "type": "username",
  "identifier": "kingchen711"
}